// Codes d'erreur au format DOMAIN_ERROR_REASON (strategy/08_STANDARDS.md §34).
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_INACTIVE: 'USER_INACTIVE',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_UNAVAILABLE: 'AUTH_ACCOUNT_UNAVAILABLE',
  AUTH_SESSION_CREATION_FAILED: 'AUTH_SESSION_CREATION_FAILED',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  // Codes refresh : diagnostic interne/audit. La réponse publique reste générique
  // (AUTH_REFRESH_TOKEN_INVALID pour la majorité des échecs externes).
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',
  // Accès protégé (Auth 4). La réponse publique normalise vers AUTH_UNAUTHORIZED ;
  // les autres codes restent du diagnostic interne/audit.
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_ACCESS_TOKEN_INVALID: 'AUTH_ACCESS_TOKEN_INVALID',
  AUTH_ACCESS_TOKEN_EXPIRED: 'AUTH_ACCESS_TOKEN_EXPIRED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  // Autorisation RBAC (Auth 5). La réponse publique d'autorisation est AUTH_FORBIDDEN (403).
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_CODE_ALREADY_EXISTS: 'ROLE_CODE_ALREADY_EXISTS',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  PERMISSION_CODE_ALREADY_EXISTS: 'PERMISSION_CODE_ALREADY_EXISTS',
  INVALID_PERMISSION_CODE: 'INVALID_PERMISSION_CODE',
  // Fichiers (ADR-007, Upload 1). Réponses publiques : 400 (validation), 404 (anti-énumération),
  // 409 (conflit de clé), 500 (persistance) ; aucun détail de stockage exposé.
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  FILE_INVALID_NAME: 'FILE_INVALID_NAME',
  FILE_INVALID_EXTENSION: 'FILE_INVALID_EXTENSION',
  FILE_INVALID_MIME_TYPE: 'FILE_INVALID_MIME_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_INVALID_STATUS: 'FILE_INVALID_STATUS',
  FILE_STORAGE_KEY_CONFLICT: 'FILE_STORAGE_KEY_CONFLICT',
  FILE_CREATION_FAILED: 'FILE_CREATION_FAILED',
  // Upload 2 (multipart + stockage objet). Réponses publiques génériques (400/413/429/503/500).
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_MULTIPART_INVALID: 'FILE_MULTIPART_INVALID',
  FILE_CONTENT_TYPE_UNDETECTED: 'FILE_CONTENT_TYPE_UNDETECTED',
  FILE_CONTENT_TYPE_MISMATCH: 'FILE_CONTENT_TYPE_MISMATCH',
  FILE_STORAGE_UNAVAILABLE: 'FILE_STORAGE_UNAVAILABLE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_FINALIZATION_FAILED: 'FILE_FINALIZATION_FAILED',
  FILE_COMPENSATION_FAILED: 'FILE_COMPENSATION_FAILED',
  FILE_ORPHANED_OBJECT_DETECTED: 'FILE_ORPHANED_OBJECT_DETECTED',
  // Upload 3 (consultation + URLs signées de lecture). Réponses publiques génériques
  // (404 anti-énumération, 409 statut, 503 stockage/signature) ; jamais de détail de stockage.
  FILE_NOT_DOWNLOADABLE: 'FILE_NOT_DOWNLOADABLE',
  FILE_SIGNED_URL_GENERATION_FAILED: 'FILE_SIGNED_URL_GENERATION_FAILED',
  FILE_STORAGE_OBJECT_MISSING: 'FILE_STORAGE_OBJECT_MISSING',
  FILE_DOWNLOAD_ACCESS_DENIED: 'FILE_DOWNLOAD_ACCESS_DENIED',
  // Upload 4 (suppression, quarantaine, réconciliation). Réponses publiques génériques
  // (404 anti-énumération, 403, 409 transition, 503 stockage, 500 DB) ; aucun détail de stockage.
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  FILE_DATABASE_FINALIZATION_FAILED: 'FILE_DATABASE_FINALIZATION_FAILED',
  FILE_ALREADY_DELETED: 'FILE_ALREADY_DELETED',
  FILE_QUARANTINE_INVALID_STATUS: 'FILE_QUARANTINE_INVALID_STATUS',
  FILE_RESTORE_INVALID_STATUS: 'FILE_RESTORE_INVALID_STATUS',
  FILE_RECONCILIATION_FAILED: 'FILE_RECONCILIATION_FAILED',
  FILE_STORAGE_LIST_FAILED: 'FILE_STORAGE_LIST_FAILED',
  // Upload 5 (quotas par propriétaire). Réponses publiques 409 (limite atteinte) ; la taille
  // individuelle dépassée reste 413 `FILE_SIZE_EXCEEDED`.
  FILE_COUNT_QUOTA_EXCEEDED: 'FILE_COUNT_QUOTA_EXCEEDED',
  FILE_STORAGE_QUOTA_EXCEEDED: 'FILE_STORAGE_QUOTA_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
