/** Audit events owned by Files. Values never carry file content or storage credentials. */
export const FILES_AUDIT_EVENTS = {
  FILE_PENDING_CREATED: 'FILE_PENDING_CREATED',
  FILE_METADATA_VALIDATED: 'FILE_METADATA_VALIDATED',
  FILE_REJECTED: 'FILE_REJECTED',
  FILE_MARKED_DELETED: 'FILE_MARKED_DELETED',
  FILE_UPLOAD_STARTED: 'FILE_UPLOAD_STARTED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_STORAGE_COMPENSATION_FAILED: 'FILE_STORAGE_COMPENSATION_FAILED',
  FILE_ORPHANED_OBJECT_DETECTED: 'FILE_ORPHANED_OBJECT_DETECTED',
  FILE_METADATA_ACCESSED: 'FILE_METADATA_ACCESSED',
  FILE_DOWNLOAD_URL_ISSUED: 'FILE_DOWNLOAD_URL_ISSUED',
  FILE_DOWNLOAD_URL_DENIED: 'FILE_DOWNLOAD_URL_DENIED',
  FILE_STORAGE_OBJECT_MISSING: 'FILE_STORAGE_OBJECT_MISSING',
  FILE_DELETION_REQUESTED: 'FILE_DELETION_REQUESTED',
  FILE_OBJECT_DELETED: 'FILE_OBJECT_DELETED',
  FILE_DELETED: 'FILE_DELETED',
  FILE_DELETION_FAILED: 'FILE_DELETION_FAILED',
  FILE_DATABASE_FINALIZATION_FAILED: 'FILE_DATABASE_FINALIZATION_FAILED',
  FILE_QUARANTINED: 'FILE_QUARANTINED',
  FILE_QUARANTINE_RELEASED: 'FILE_QUARANTINE_RELEASED',
  FILE_RECONCILIATION_STARTED: 'FILE_RECONCILIATION_STARTED',
  FILE_RECONCILIATION_COMPLETED: 'FILE_RECONCILIATION_COMPLETED',
  FILE_RECONCILIATION_ACTION: 'FILE_RECONCILIATION_ACTION',
  FILE_PENDING_EXPIRED: 'FILE_PENDING_EXPIRED',
  FILE_ORPHAN_DELETED: 'FILE_ORPHAN_DELETED',
  FILE_QUOTA_EXCEEDED: 'FILE_QUOTA_EXCEEDED',
} as const;

export type FilesAuditEvent = (typeof FILES_AUDIT_EVENTS)[keyof typeof FILES_AUDIT_EVENTS];
export type AuditEventType = FilesAuditEvent;
