import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { access, mkdtemp, readFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  orderCapabilitySeeds,
  renderExpoHomeActions,
  renderNextjsDashboardNav,
  renderNextjsStatusSections,
  renderPrismaSeedRegistry,
} from '../engine/overlay-renderers.mjs';
import { validateOverwriteUsage, GOVERNED_FILES, OVERWRITE_ALLOWLIST } from '../engine/overwrite-policy.mjs';
import { validateOverlayManifest } from '../engine/overlay.mjs';
import { createDefaultBlueprint } from '../engine/blueprint.mjs';
import { generateProject } from '../engine/generator.mjs';

async function exists(p) { try { await access(p, constants.F_OK); return true; } catch { return false; } }

function blueprint(slug, capabilities, stack = { api: 'nestjs', web: 'nextjs', mobile: null }) {
  const b = createDefaultBlueprint(slug);
  b.stack = stack;
  b.capabilities = capabilities;
  b.designSystem = true;
  b.deployment = { environments: ['local'] };
  return b;
}

const seed = (symbol, order, capability = 'x') => ({ kind: 'nestjs.prisma-seed', importPath: `./${symbol}`, symbol, order, capability });
const section = (symbol, order, capability = 'x') => ({ kind: 'nextjs.status-section', importPath: `@/${symbol}`, symbol, order, capability });
const dashboardLink = (href, label, order, capability = 'x') => ({ kind: 'nextjs.dashboard-nav-link', href, label, order, capability });
const homeAction = (href, label, order, capability = 'x') => ({ kind: 'expo.home-action', href, label, order, capability });

describe('composable seed', () => {
  it('orders seeds by declared order', () => {
    const ordered = orderCapabilitySeeds([seed('seedFiles', 30), seed('seedAuth', 10), seed('seedRbac', 20)]);
    assert.deepEqual(ordered.map((s) => s.symbol), ['seedAuth', 'seedRbac', 'seedFiles']);
  });

  it('rejects a duplicated seed symbol and an ambiguous rank', () => {
    assert.throws(() => orderCapabilitySeeds([seed('seedRbac', 10), seed('seedRbac', 20)]), /Duplicate capability seed/);
    assert.throws(() => orderCapabilitySeeds([seed('seedRbac', 10), seed('seedFiles', 10)]), /Ambiguous capability seed order/);
  });

  it('renders a registry consumed by the stable orchestrator', () => {
    const rendered = renderPrismaSeedRegistry([seed('seedRbac', 20, 'rbac'), seed('seedAuth', 10, 'auth')]);
    assert.ok(rendered.indexOf('seedAuth') < rendered.indexOf('seedRbac'), 'ordered registry');
    assert.match(rendered, /CAPABILITY_SEEDS/);
    assert.match(rendered, /run: seedRbac/);
  });

  it('generates the registry and never replaces the seed orchestrator', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-seed-'));
    const out = join(root, 'p');
    await generateProject(blueprint('seed-app', ['base', 'auth', 'rbac']), out);
    const registry = await readFile(join(out, 'apps/api/prisma/seed/capability-seeds.ts'), 'utf8');
    assert.match(registry, /GENERATED BY ENISTERE FACTORY/);
    assert.match(registry, /run: seedRbac/);
    // The orchestrator stays the baseline file: it only iterates the registry.
    const orchestrator = await readFile(join(out, 'apps/api/prisma/seed.ts'), 'utf8');
    assert.match(orchestrator, /CAPABILITY_SEEDS/);
    assert.ok(!/seedRbac/.test(orchestrator), 'orchestrator is capability-agnostic');
  });

  it('leaves an empty registry for base + auth', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-seed-auth-'));
    const out = join(root, 'p');
    await generateProject(blueprint('seed-auth', ['base', 'auth']), out);
    const registry = await readFile(join(out, 'apps/api/prisma/seed/capability-seeds.ts'), 'utf8');
    assert.match(registry, /CAPABILITY_SEEDS: readonly CapabilitySeed\[\] = \[\]/);
  });
});

describe('composed e2e test environment', () => {
  // `test/setup-e2e.ts` is allowlisted for overwrite: exactly one variant exists per
  // composition, so the last capability composed must supply a strict superset.
  it('supplies the Files test variables when Files is composed', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-env-files-'));
    const out = join(root, 'p');
    await generateProject(blueprint('env-files', ['base', 'auth', 'rbac', 'files']), out);
    const setup = await readFile(join(out, 'apps/api/test/setup-e2e.ts'), 'utf8');
    // Production default (86400 s) would make reconciliation untestable.
    assert.match(setup, /FILES_ORPHAN_MIN_AGE_SECONDS \?\?= '1'/);
    assert.match(setup, /S3_BUCKET \?\?=/);
    // Superset: the Auth and baseline variables survive the replacement.
    assert.match(setup, /JWT_ACCESS_SECRET \?\?=/);
    assert.match(setup, /ARGON2_MEMORY_COST \?\?= '512'/);
    assert.match(setup, /DATABASE_URL \?\?=/);
  });

  it('leaves the Auth variant untouched without Files', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-env-auth-'));
    const out = join(root, 'p');
    await generateProject(blueprint('env-auth', ['base', 'auth']), out);
    const setup = await readFile(join(out, 'apps/api/test/setup-e2e.ts'), 'utf8');
    assert.match(setup, /JWT_ACCESS_SECRET \?\?=/);
    assert.ok(!/FILES_ORPHAN_MIN_AGE_SECONDS/.test(setup), 'no Files surface without Files');
  });
});

describe('composable Next.js status sections', () => {
  it('orders sections and rejects duplicates or ambiguous ranks', () => {
    const rendered = renderNextjsStatusSections([section('B', 20, 'rbac'), section('A', 10, 'auth')]);
    assert.ok(rendered.indexOf('Component: A') < rendered.indexOf('Component: B'));
    assert.throws(() => renderNextjsStatusSections([section('A', 10), section('A', 20)]), /Duplicate status section/);
    assert.throws(() => renderNextjsStatusSections([section('A', 10), section('B', 10)]), /Ambiguous status section order/);
  });

  it('registers only the session panel for base + auth', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-sec-auth-'));
    const out = join(root, 'p');
    await generateProject(blueprint('sec-auth', ['base', 'auth']), out);
    const registry = await readFile(join(out, 'apps/web/src/core/composition/status-sections.tsx'), 'utf8');
    assert.match(registry, /SessionPanel/);
    assert.ok(!/AuthorizationPanel/.test(registry), 'no RBAC residue');
  });

  it('registers both panels, ordered, for base + auth + rbac', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-sec-rbac-'));
    const out = join(root, 'p');
    await generateProject(blueprint('sec-rbac', ['base', 'auth', 'rbac']), out);
    const registry = await readFile(join(out, 'apps/web/src/core/composition/status-sections.tsx'), 'utf8');
    assert.ok(registry.indexOf('Component: SessionPanel') < registry.indexOf('Component: AuthorizationPanel'));
    // The shared shell page is never replaced by a capability.
    const page = await readFile(join(out, 'apps/web/src/app/(public)/status/page.tsx'), 'utf8');
    assert.match(page, /CapabilityStatusSections/);
    assert.ok(!/AuthorizationPanel/.test(page), 'shell stays capability-agnostic');
  });

  it('keeps an empty registry for base alone', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-sec-base-'));
    const out = join(root, 'p');
    await generateProject(blueprint('sec-base', ['base']), out);
    const registry = await readFile(join(out, 'apps/web/src/core/composition/status-sections.tsx'), 'utf8');
    assert.match(registry, /CAPABILITY_STATUS_SECTIONS: readonly CapabilityStatusSection\[\] = \[\]/);
  });
});

describe('composable capability navigation', () => {
  it('orders Next.js links and rejects duplicate destinations or ranks', () => {
    const rendered = renderNextjsDashboardNav([
      dashboardLink('/protected/files', 'Fichiers', 20, 'files'),
      dashboardLink('/protected', 'Accueil', 10, 'auth'),
    ]);
    assert.ok(rendered.indexOf('href: "/protected"') < rendered.indexOf('href: "/protected/files"'));
    assert.throws(() => renderNextjsDashboardNav([
      dashboardLink('/protected', 'Accueil', 10), dashboardLink('/protected', 'Autre', 20),
    ]), /Duplicate dashboard link href/);
    assert.throws(() => renderNextjsDashboardNav([
      dashboardLink('/protected', 'Accueil', 10), dashboardLink('/protected/files', 'Fichiers', 10),
    ]), /Ambiguous dashboard link order/);
  });

  it('orders Expo actions and rejects duplicate destinations or ranks', () => {
    const rendered = renderExpoHomeActions([
      homeAction('/upload', 'Envoyer un fichier', 20, 'files'),
      homeAction('/settings', 'Parametres', 10, 'auth'),
    ]);
    assert.ok(rendered.indexOf("href: '/settings'") < rendered.indexOf("href: '/upload'"));
    assert.throws(() => renderExpoHomeActions([
      homeAction('/settings', 'Parametres', 10), homeAction('/settings', 'Autre', 20),
    ]), /Duplicate home action href/);
    assert.throws(() => renderExpoHomeActions([
      homeAction('/settings', 'Parametres', 10), homeAction('/upload', 'Upload', 10),
    ]), /Ambiguous home action order/);
  });

  it('generates only Auth navigation without Files', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-nav-auth-'));
    const out = join(root, 'p');
    await generateProject(blueprint('nav-auth', ['base', 'auth'], {
      api: 'nestjs', web: 'nextjs', mobile: 'react-native',
    }), out);
    const web = await readFile(join(out, 'apps/web/src/core/composition/dashboard-nav.ts'), 'utf8');
    const mobile = await readFile(join(out, 'apps/mobile/src/composition/home-actions.ts'), 'utf8');
    assert.match(web, /\/protected/);
    assert.ok(!web.includes('/protected/files'));
    assert.match(mobile, /\/settings/);
    assert.ok(!mobile.includes('/upload'));
  });

  it('adds Files navigation without replacing either shell', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-nav-files-'));
    const out = join(root, 'p');
    await generateProject(blueprint('nav-files', ['base', 'auth', 'rbac', 'files'], {
      api: 'nestjs', web: 'nextjs', mobile: 'react-native',
    }), out);
    const web = await readFile(join(out, 'apps/web/src/core/composition/dashboard-nav.ts'), 'utf8');
    const mobile = await readFile(join(out, 'apps/mobile/src/composition/home-actions.ts'), 'utf8');
    assert.match(web, /\/protected\/files/);
    assert.match(web, /\/protected\/files\/upload/);
    assert.match(mobile, /\/upload/);
    assert.match(await readFile(join(out, 'apps/web/src/features/dashboard/dashboard-shell.tsx'), 'utf8'), /CAPABILITY_DASHBOARD_LINKS/);
    assert.match(await readFile(join(out, 'apps/mobile/app/(app)/home.tsx'), 'utf8'), /CAPABILITY_HOME_ACTIONS/);
  });
});

describe('overwrite policy', () => {
  const file = (destination, overwrite = true) => ({ source: 'files/x', destination, overwrite });

  it('refuses overwriting governed central files', () => {
    for (const { path } of GOVERNED_FILES) {
      const issues = validateOverwriteUsage([file(path)]);
      assert.equal(issues.length, 1, path);
      assert.match(issues[0], /governed central file/);
    }
  });

  it('refuses an overwrite that is not allowlisted', () => {
    const issues = validateOverwriteUsage([file('src/features/whatever.ts')]);
    assert.match(issues[0], /not in the overwrite allowlist/);
  });

  it('accepts the documented allowlist', () => {
    for (const { path } of OVERWRITE_ALLOWLIST) {
      assert.deepEqual(validateOverwriteUsage([file(path)]), [], path);
    }
  });

  it('documents a justification for every allowlisted file', () => {
    for (const entry of OVERWRITE_ALLOWLIST) {
      assert.ok(entry.reason && entry.reason.length > 30, `${entry.path} needs a justification`);
    }
  });

  it('refuses governed files even without an overwrite flag', () => {
    const issues = validateOverwriteUsage([{ source: 'files/x', destination: 'prisma/seed.ts' }]);
    assert.equal(issues.length, 1);
    assert.match(issues[0], /cannot be supplied by a file operation/);
  });

  it('is enforced by overlay validation', () => {
    const issues = validateOverlayManifest({
      schemaVersion: '1', capability: 'rbac', target: 'nestjs', version: '0.2.0',
      files: [file('openapi/openapi.json')], dependencies: {}, environment: [], integrations: [], verification: [],
    });
    assert.ok(issues.some((i) => /governed central file/.test(i)), issues.join(' '));
  });

  it('is respected by every shipped overlay', async () => {
    for (const capability of ['auth', 'rbac', 'files']) {
      for (const target of ['nestjs', 'nextjs', 'react-native']) {
        const path = new URL(`../../capabilities/${capability}/targets/${target}/overlay.json`, import.meta.url);
        if (!(await exists(path))) continue;
        const manifest = JSON.parse(await readFile(path, 'utf8'));
        assert.deepEqual(
          validateOverwriteUsage(manifest.files),
          [],
          `${capability}/${target} violates the overwrite policy`,
        );
      }
    }
  });
});

describe('composable OpenAPI contract', () => {
  it('declares expected operations per capability instead of shipping a snapshot', async () => {
    for (const [capability, expected] of [
      ['auth', ['auth_login', 'auth_refresh', 'auth_logout', 'auth_getProfile']],
      ['rbac', ['auth_getAuthorization']],
      ['files', [
        'files_list', 'files_upload', 'files_getMetadata', 'files_createDownloadUrl',
        'files_delete', 'files_quarantine', 'files_restore',
      ]],
    ]) {
      const manifest = JSON.parse(await readFile(
        new URL(`../../capabilities/${capability}/targets/nestjs/overlay.json`, import.meta.url), 'utf8',
      ));
      assert.deepEqual(manifest.contract.openapiOperations, expected);
      // No overlay ships an OpenAPI snapshot any more.
      assert.ok(
        !manifest.files.some((f) => f.destination === 'openapi/openapi.json'),
        `${capability} must not ship an OpenAPI snapshot`,
      );
    }
  });

  it('records the declared operations in the generated lock', async () => {
    const root = await mkdtemp(join(tmpdir(), 'enistere-contract-'));
    const out = join(root, 'p');
    await generateProject(blueprint('contract-app', ['base', 'auth', 'rbac']), out);
    const lock = JSON.parse(await readFile(join(out, 'enistere.lock'), 'utf8'));
    const nestjs = lock.overlays.filter((o) => o.target === 'nestjs');
    const operations = nestjs.flatMap((o) => o.openapiOperations ?? []).sort();
    assert.deepEqual(operations, [
      'auth_getAuthorization', 'auth_getProfile', 'auth_login', 'auth_logout', 'auth_refresh',
    ]);
  });

  it('rejects a malformed contract declaration', () => {
    const base = {
      schemaVersion: '1', capability: 'rbac', target: 'nestjs', version: '0.2.0',
      files: [], dependencies: {}, environment: [], integrations: [], verification: [],
    };
    assert.ok(validateOverlayManifest({ ...base, contract: { openapiOperations: [''] } })
      .some((i) => /openapiOperations/.test(i)));
    assert.ok(validateOverlayManifest({ ...base, contract: { unknown: true } })
      .some((i) => /contract.unknown is not supported/.test(i)));
    assert.ok(validateOverlayManifest({ ...base, contract: { openapiOperations: ['auth_login', 'auth_login'] } })
      .some((i) => /must not contain duplicates/.test(i)));
    assert.ok(validateOverlayManifest({
      ...base,
      target: 'nextjs',
      contract: { openapiOperations: ['auth_login'] },
    }).some((i) => /supported only for the nestjs target/.test(i)));
  });
});
