/**
 * NestJS domain renderer (R9).
 *
 * Turns blueprint `domain.entities` into a full CRUD vertical per entity: a
 * Prisma model (contributed to the typed schema composition), a Prisma-backed
 * service, validated DTOs, and a REST controller whose operationIds match the
 * neutral OpenAPI contract (`list<Entity>`/`create<Entity>`/…). The module is
 * wired through the standard `nestjs.module` composition seam; the contribution
 * declares `contract.openapiOperations` so the composed application's regenerated
 * OpenAPI is verified to expose exactly the base + domain operations
 * (golden-runtime `verifyComposedOpenApi`, like any capability that adds routes).
 */

const DOMAIN_RENDERER_VERSION = '0.2.0';

const PRISMA_SCALAR = { uuid: 'String', string: 'String', integer: 'Int', number: 'Float', boolean: 'Boolean', datetime: 'DateTime' };
const TS_SCALAR = { uuid: 'string', string: 'string', integer: 'number', number: 'number', boolean: 'boolean', datetime: 'string' };
const VALIDATOR = { uuid: 'IsUUID', string: 'IsString', integer: 'IsInt', number: 'IsNumber', boolean: 'IsBoolean', datetime: 'IsDateString' };

function kebab(name) { return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase(); }
function snake(name) { return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase(); }
function delegate(name) { return name[0].toLowerCase() + name.slice(1); }

const BANNER = (entity) => `// GENERATED BY ENISTERE FACTORY — domain '${entity.name}'. Do not edit manually.`;

function prismaField(field) {
  const scalar = PRISMA_SCALAR[field.type] ?? 'String';
  const optional = field.required ? '' : '?';
  const attributes = [];
  if (field.name === 'id') {
    attributes.push('@id');
    if (field.type === 'uuid') attributes.push('@default(uuid())', '@db.Uuid');
  } else if (field.type === 'uuid') {
    attributes.push('@db.Uuid');
  }
  return { name: field.name, type: `${scalar}${optional}`, ...(attributes.length ? { attributes } : {}) };
}

function prismaModel(entity) {
  return { name: entity.name, fields: entity.fields.map(prismaField), blockAttributes: [`@@map("${snake(entity.name)}s")`] };
}

function dtoFile(entity) {
  const writable = entity.fields.filter((field) => field.name !== 'id');
  const validators = new Set();
  let usesOptional = false;
  let usesMaxLength = false;
  const lines = [];
  for (const field of writable) {
    const ts = TS_SCALAR[field.type] ?? 'string';
    validators.add(VALIDATOR[field.type] ?? 'IsString');
    if (field.required) {
      lines.push(`  @ApiProperty()`);
    } else {
      lines.push(`  @ApiPropertyOptional()`);
      lines.push(`  @IsOptional()`);
      usesOptional = true;
    }
    lines.push(`  @${VALIDATOR[field.type] ?? 'IsString'}()`);
    if (field.type === 'string' && field.maxLength) { lines.push(`  @MaxLength(${field.maxLength})`); usesMaxLength = true; }
    lines.push(`  ${field.name}${field.required ? '!' : '?'}: ${ts};`);
    lines.push('');
  }
  if (lines.at(-1) === '') lines.pop();
  if (usesMaxLength) validators.add('MaxLength');
  if (usesOptional) validators.add('IsOptional');
  const validatorImport = [...validators].sort();
  return [
    BANNER(entity),
    `import { ApiProperty, ApiPropertyOptional, PartialType } from '@nestjs/swagger';`,
    `import { ${validatorImport.join(', ')} } from 'class-validator';`,
    '',
    `export class Create${entity.name}Dto {`,
    ...lines,
    '}',
    '',
    `export class Update${entity.name}Dto extends PartialType(Create${entity.name}Dto) {}`,
    '',
  ].join('\n');
}

function serviceFile(entity) {
  const model = delegate(entity.name);
  return [
    BANNER(entity),
    "import { Injectable } from '@nestjs/common';",
    '',
    "import { PrismaService } from '../../database/prisma.service';",
    `import type { Create${entity.name}Dto, Update${entity.name}Dto } from './${kebab(entity.name)}.dto';`,
    '',
    '/** Prisma-backed CRUD for the domain entity (application boundary). */',
    '@Injectable()',
    `export class ${entity.name}Service {`,
    '  constructor(private readonly prisma: PrismaService) {}',
    '',
    `  list() {`,
    `    return this.prisma.${model}.findMany();`,
    '  }',
    '',
    `  create(input: Create${entity.name}Dto) {`,
    `    return this.prisma.${model}.create({ data: input });`,
    '  }',
    '',
    '  get(id: string) {',
    `    return this.prisma.${model}.findUnique({ where: { id } });`,
    '  }',
    '',
    `  update(id: string, input: Update${entity.name}Dto) {`,
    `    return this.prisma.${model}.update({ where: { id }, data: input });`,
    '  }',
    '',
    '  remove(id: string) {',
    `    return this.prisma.${model}.delete({ where: { id } });`,
    '  }',
    '}',
    '',
  ].join('\n');
}

function controllerFile(entity) {
  const svc = `${delegate(entity.name)}Service`;
  return [
    BANNER(entity),
    "import { Body, Controller, Delete, Get, Param, Patch, Post } from '@nestjs/common';",
    "import { ApiOperation, ApiTags } from '@nestjs/swagger';",
    '',
    `import { Create${entity.name}Dto, Update${entity.name}Dto } from './${kebab(entity.name)}.dto';`,
    `import { ${entity.name}Service } from './${kebab(entity.name)}.service';`,
    '',
    `@ApiTags('${entity.name}')`,
    `@Controller('${kebab(entity.name)}')`,
    `export class ${entity.name}Controller {`,
    `  constructor(private readonly ${svc}: ${entity.name}Service) {}`,
    '',
    '  @Get()',
    `  @ApiOperation({ operationId: 'list${entity.name}' })`,
    `  list() {`,
    `    return this.${svc}.list();`,
    '  }',
    '',
    '  @Post()',
    `  @ApiOperation({ operationId: 'create${entity.name}' })`,
    `  create(@Body() input: Create${entity.name}Dto) {`,
    `    return this.${svc}.create(input);`,
    '  }',
    '',
    "  @Get(':id')",
    `  @ApiOperation({ operationId: 'get${entity.name}' })`,
    `  get(@Param('id') id: string) {`,
    `    return this.${svc}.get(id);`,
    '  }',
    '',
    "  @Patch(':id')",
    `  @ApiOperation({ operationId: 'update${entity.name}' })`,
    `  update(@Param('id') id: string, @Body() input: Update${entity.name}Dto) {`,
    `    return this.${svc}.update(id, input);`,
    '  }',
    '',
    "  @Delete(':id')",
    `  @ApiOperation({ operationId: 'delete${entity.name}' })`,
    `  remove(@Param('id') id: string) {`,
    `    return this.${svc}.remove(id);`,
    '  }',
    '}',
    '',
  ].join('\n');
}

function moduleFile(entity) {
  return [
    BANNER(entity),
    "import { Module } from '@nestjs/common';",
    '',
    `import { ${entity.name}Controller } from './${kebab(entity.name)}.controller';`,
    `import { ${entity.name}Service } from './${kebab(entity.name)}.service';`,
    '',
    '@Module({',
    `  controllers: [${entity.name}Controller],`,
    `  providers: [${entity.name}Service],`,
    `  exports: [${entity.name}Service],`,
    '})',
    `export class ${entity.name}Module {}`,
    '',
  ].join('\n');
}

const CRUD_ACTIONS = ['list', 'create', 'get', 'update', 'delete'];

/**
 * Renders the domain contribution for NestJS: in-memory files, an inline Prisma
 * fragment, `nestjs.module` integrations, and the OpenAPI operations the composed
 * app will expose. Requires each entity to declare an `id` field (CRUD key).
 */
export function renderNestjsDomain(entities) {
  const files = [];
  const models = [];
  const integrations = [];
  const openapiOperations = [];
  for (const entity of entities) {
    if (!entity.fields.some((field) => field.name === 'id')) {
      throw new Error(`domain entity ${entity.name} must declare an 'id' field to generate CRUD`);
    }
    const dir = `src/domain/${kebab(entity.name)}`;
    const base = `${dir}/${kebab(entity.name)}`;
    files.push({ destination: `${base}.dto.ts`, contents: dtoFile(entity) });
    files.push({ destination: `${base}.service.ts`, contents: serviceFile(entity) });
    files.push({ destination: `${base}.controller.ts`, contents: controllerFile(entity) });
    files.push({ destination: `${base}.module.ts`, contents: moduleFile(entity) });
    models.push(prismaModel(entity));
    integrations.push({ kind: 'nestjs.module', importPath: `../domain/${kebab(entity.name)}/${kebab(entity.name)}.module`, symbol: `${entity.name}Module` });
    for (const action of CRUD_ACTIONS) openapiOperations.push(`${action}${entity.name}`);
  }
  return {
    version: DOMAIN_RENDERER_VERSION,
    files,
    prisma: { enums: [], models },
    integrations,
    contract: { openapiOperations },
  };
}
