/**
 * NestJS domain renderer (R9, first slice).
 *
 * Turns blueprint `domain.entities` into a persistence + typed service layer per
 * entity: a Prisma model (contributed to the typed schema composition), a
 * Prisma-backed CRUD service, its input types, and a module wired through the
 * standard `nestjs.module` composition seam. It reuses the exact conventions of
 * the NestJS starter (global `DatabaseModule`/`PrismaService`, capability
 * modules imported by `AppModule`). HTTP controllers + OpenAPI snapshot
 * integration are a following slice; this layer adds no routes, so the
 * generated project's `openapi:check` stays green.
 */

const DOMAIN_RENDERER_VERSION = '0.1.0';

const PRISMA_SCALAR = { uuid: 'String', string: 'String', integer: 'Int', number: 'Float', boolean: 'Boolean', datetime: 'DateTime' };
const TS_SCALAR = { uuid: 'string', string: 'string', integer: 'number', number: 'number', boolean: 'boolean', datetime: 'Date' };

function kebab(name) { return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase(); }
function snake(name) { return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase(); }
function delegate(name) { return name[0].toLowerCase() + name.slice(1); }

function prismaField(field) {
  const scalar = PRISMA_SCALAR[field.type] ?? 'String';
  const optional = field.required ? '' : '?';
  const attributes = [];
  if (field.name === 'id') {
    attributes.push('@id');
    if (field.type === 'uuid') attributes.push('@default(uuid())', '@db.Uuid');
  } else if (field.type === 'uuid') {
    attributes.push('@db.Uuid');
  }
  return { name: field.name, type: `${scalar}${optional}`, ...(attributes.length ? { attributes } : {}) };
}

function prismaModel(entity) {
  return {
    name: entity.name,
    fields: entity.fields.map(prismaField),
    blockAttributes: [`@@map("${snake(entity.name)}s")`],
  };
}

function tsType(field) {
  const scalar = TS_SCALAR[field.type] ?? 'string';
  return field.required ? scalar : `${scalar} | null`;
}

function typesFile(entity) {
  const writable = entity.fields.filter((field) => field.name !== 'id');
  const createLines = writable.map((field) => `  readonly ${field.name}${field.required ? '' : '?'}: ${tsType(field)};`);
  return [
    `// GENERATED BY ENISTERE FACTORY — domain '${entity.name}'. Do not edit manually.`,
    '',
    `export interface Create${entity.name}Input {`,
    ...createLines,
    '}',
    '',
    `export type Update${entity.name}Input = Partial<Create${entity.name}Input>;`,
    '',
  ].join('\n');
}

function serviceFile(entity) {
  const model = delegate(entity.name);
  return [
    `// GENERATED BY ENISTERE FACTORY — domain '${entity.name}'. Do not edit manually.`,
    "import { Injectable } from '@nestjs/common';",
    '',
    "import { PrismaService } from '../../database/prisma.service';",
    `import type { Create${entity.name}Input, Update${entity.name}Input } from './${kebab(entity.name)}.types';`,
    '',
    '/** Prisma-backed CRUD for the domain entity (application boundary). */',
    '@Injectable()',
    `export class ${entity.name}Service {`,
    '  constructor(private readonly prisma: PrismaService) {}',
    '',
    `  list() {`,
    `    return this.prisma.${model}.findMany();`,
    '  }',
    '',
    `  create(input: Create${entity.name}Input) {`,
    `    return this.prisma.${model}.create({ data: input });`,
    '  }',
    '',
    '  get(id: string) {',
    `    return this.prisma.${model}.findUnique({ where: { id } });`,
    '  }',
    '',
    `  update(id: string, input: Update${entity.name}Input) {`,
    `    return this.prisma.${model}.update({ where: { id }, data: input });`,
    '  }',
    '',
    '  remove(id: string) {',
    `    return this.prisma.${model}.delete({ where: { id } });`,
    '  }',
    '}',
    '',
  ].join('\n');
}

function moduleFile(entity) {
  return [
    `// GENERATED BY ENISTERE FACTORY — domain '${entity.name}'. Do not edit manually.`,
    "import { Module } from '@nestjs/common';",
    '',
    `import { ${entity.name}Service } from './${kebab(entity.name)}.service';`,
    '',
    '@Module({',
    `  providers: [${entity.name}Service],`,
    `  exports: [${entity.name}Service],`,
    '})',
    `export class ${entity.name}Module {}`,
    '',
  ].join('\n');
}

/**
 * Renders the domain contribution for NestJS: in-memory files, an inline Prisma
 * fragment, and `nestjs.module` integrations. Requires each entity to declare an
 * `id` field (the CRUD primary key).
 */
export function renderNestjsDomain(entities) {
  const files = [];
  const models = [];
  const integrations = [];
  for (const entity of entities) {
    if (!entity.fields.some((field) => field.name === 'id')) {
      throw new Error(`domain entity ${entity.name} must declare an 'id' field to generate CRUD`);
    }
    const dir = `src/domain/${kebab(entity.name)}`;
    files.push({ destination: `${dir}/${kebab(entity.name)}.types.ts`, contents: typesFile(entity) });
    files.push({ destination: `${dir}/${kebab(entity.name)}.service.ts`, contents: serviceFile(entity) });
    files.push({ destination: `${dir}/${kebab(entity.name)}.module.ts`, contents: moduleFile(entity) });
    models.push(prismaModel(entity));
    integrations.push({ kind: 'nestjs.module', importPath: `../domain/${kebab(entity.name)}/${kebab(entity.name)}.module`, symbol: `${entity.name}Module` });
  }
  return {
    version: DOMAIN_RENDERER_VERSION,
    files,
    prisma: { enums: [], models },
    integrations,
  };
}
